# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=1.21.11
supported_minecraft_versions=1.21.11
loader_version=0.18.4

# Mod Properties
mod_version=2.0.0
mod_build=
maven_group=com.github.command17
archives_base_name=fabricdiscordbridge

# Dependencies
fabric_version=0.141.1+1.21.11
jda_version=6.1.0
config_builder_version=2.1.0

# Publish
# release_type: ALPHA, BETA, STABLE
release_type = STABLE
branch = main